[mypy]
ignore_missing_imports = True

[pytest]
minversion = 6.0.0

testpaths = maddness/python/tests src/python/test

python_files = test*.py

# always run in parallel (requires pytest-xdist, see test-requirements.txt)
# and enable strict mode: require all markers
# to be defined and raise on invalid config values
addopts = -nauto --strict-markers --strict-config

# treat xpasses as test failures so they get converted to regular tests as soon as possible
xfail_strict = true