[tool.mypy]
ignore_missing_imports = true
files = ["maddness/python", "src/python"]

[tool.pytest.ini_options]
pythonpath = ["src/python"]

markers = [
  "heavy", # should be run independent in CI
]

minversion = "6.0.0"

testpaths = ["src/python/test"]

python_files = "test*.py"

addopts = "-nauto --strict-markers --strict-config -v"

# always run in parallel (requires pytest-xdist to be installed)
# and enable strict mode: require all markers
# to be defined and raise on invalid config values
# treat xpasses as test failures so they get converted to regular tests as soon as possible
xfail_strict = true

[tool.pylint]

# Use multiple processes to speed up Pylint.
jobs = 4

ignore-paths = [
  "^maddness/python/joblib/.*$",
  "^src/python/results/*$",
  "^src/python/runs/*$",
]

ignore-patterns = [
  ".*.json",
  ".*.pth",
  ".*.core",
  ".*.sh",
  ".*.log",
  ".*.txt",
  ".*.npy",
  ".*.png",
  ".*.csv",
]
# init-hook='import sys; sys.path.append("./maddness/python/")'

max-line-length = 100

enable = "bad-indentation" # Used when an unexpected number of indentation’s tabulations or spaces has been found.unnecessary-semicolon, # Used when a statement is ended by a semi-colon (”;”), which isn’t necessary.unused-variable        # Used when a variable is defined but not used. (Use _var to ignore var).

disable = [
  "import-error",
  "missing-module-docstring",
  "invalid-name",
  "missing-function-docstring",
  "redefined-outer-name",
  "missing-class-docstring",
  "too-many-locals",
  "too-few-public-methods",
  "unused-import",
  "pointless-string-statement",
  "too-many-statements",
  "too-many-arguments",
  "no-name-in-module",
  "fixme",
  "too-many-branches",
  "multiple-imports",
  "duplicate-code",
  "inconsistent-return-statements",
  "consider-using-min-builtin",
  "too-many-instance-attributes",
  "consider-using-f-string",
  "no-else-return",
  "no-else-raise",
  "unspecified-encoding",
  "broad-except",
  "redefined-builtin",
  "trailing-newlines",
  "dangerous-default-value",
  "too-many-lines",
  "broad-exception-raised",
]

reports = false

score = false


# Tells whether to display a full report or only the messages
# Activate the evaluation score.

# Exceptions that will emit a warning when being caught.

# Minimum lines number of a similarity.
min-similarity-lines = 5


generated-members = ["numpy.*", "torch.*"]
# List of members which are set dynamically and missed by Pylint inference
# system, and so shouldn't trigger E1101 when accessed.
