name: HW Design Verification

on: push

jobs:
  changes:
    uses: ./.github/workflows/filter.yaml

  icarus_simulations:
    needs: changes
    if: ${{ needs.changes.outputs.hardware == 'true' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.oi/joennlae/halutmatmul-conda-hw:latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - name: Simulate and run DV with icarus
        run: |
          source /venv/bin/activate
          cd hardware
          RESULT=0
          fusesoc --cores-root=. run --target=icarus halut:test:scm
          RESULT=$(($RESULT + $?))
          fusesoc --cores-root=. run --target=icarus halut:test:fp_adder
          RESULT=$(($RESULT + $?))
          fusesoc --cores-root=. run --target=icarus halut:test:fp_16_to_32_convert
          RESULT=$(($RESULT + $?))
          fusesoc --cores-root=. run --target=icarus halut:test:fp_16_32_adder
          RESULT=$(($RESULT + $?))
          fusesoc --cores-root=. run --target=icarus halut:test:fp_16_comparision
          RESULT=$(($RESULT + $?))
          fusesoc --cores-root=. run --target=icarus halut:test:halut_encoder
          RESULT=$(($RESULT + $?))
          fusesoc --cores-root=. run --target=icarus halut:test:halut_decoder
          RESULT=$(($RESULT + $?))
          fusesoc --cores-root=. run --target=icarus halut:test:halut_encoder_4
          RESULT=$(($RESULT + $?))
          fusesoc --cores-root=. run --target=icarus halut:test:halut_decoder_x
          RESULT=$(($RESULT + $?))
          fusesoc --cores-root=. run --target=icarus halut:test:halut_matmul
          RESULT=$(($RESULT + $?))
          NUM_C=16 NUM_DECODER_UNITS=8 fusesoc --cores-root=. run --target=icarus halut:test:halut_matmul
          RESULT=$(($RESULT + $?))
          NUM_C=64 fusesoc --cores-root=. run --target=icarus halut:test:halut_matmul
          RESULT=$(($RESULT + $?))

          echo "Exit Code: $RESULT"
          exit $RESULT
