name: HW Design Verification

on: push

jobs:
  changes:
    uses: ./.github/workflows/filter.yaml

  rtl-simulations-icarus:
    needs: changes
    if: ${{ needs.changes.outputs.hardware == 'true' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joennlae/halutmatmul-conda-hw:latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - name: Simulate and run DV with icarus for subunits
        run: |
          source /venv/bin/activate
          cd hardware
          RESULT=0
          make test-scm
          RESULT=$(($RESULT + $?))
          ACC_TYPE=FP32 make test-fp-adder
          RESULT=$(($RESULT + $?))
          ACC_TYPE=FP32 make test-fp-16-to-32-convert
          RESULT=$(($RESULT + $?))
          ACC_TYPE=FP32 make test-fp-16-32-adder
          RESULT=$(($RESULT + $?))
          ACC_TYPE=FP32 make test-fp-16-comparision
          RESULT=$(($RESULT + $?))
          make test-halut-encoder
          RESULT=$(($RESULT + $?))
          make test-halut-decoder
          RESULT=$(($RESULT + $?))
          make test-halut-encoder-4
          RESULT=$(($RESULT + $?))
          make test-halut-decoder-x
          RESULT=$(($RESULT + $?))
          ACC_TYPE=INT DATA_WIDTH=8 make test-mixed-int-adder
          RESULT=$(($RESULT + $?))

          echo "Exit Code: $RESULT"
          exit $RESULT

  rtl-simulations-icarus-large:
    needs: changes
    if: ${{ needs.changes.outputs.hardware == 'true' }}
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joennlae/halutmatmul-conda-hw:latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v3
      - name: Simulate and run DV with icarus for top level
        run: |
          source /venv/bin/activate
          cd hardware
          RESULT=0
          make test-halut-matmul
          RESULT=$(($RESULT + $?))
          NUM_C=16 NUM_DECODER_UNITS=4 make test-halut-matmul
          RESULT=$(($RESULT + $?))
          NUM_C=32 NUM_DECODER_UNITS=4 make test-halut-matmul
          RESULT=$(($RESULT + $?))
          DATA_WIDTH=8 ACC_TYPE=INT make test-halut-matmul
          RESULT=$(($RESULT + $?))

          echo "Exit Code: $RESULT"
          exit $RESULT
