name: Linting

on: push

jobs:

  lint_python:
    name: Python Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Python Pylint Github Action
        uses: fylein/python-pylint-github-action@v4
        with:
          args: pylint --rcfile=.pylintrc maddness/python/*
