name: Pyright - Typechecking
# https://autobencoder.com/2020-08-24-conda-actions/
on: [push]

jobs:
  changes:
    uses: ./.github/workflows/filter.yaml
  python_typechecking:
    needs: changes
    if: ${{ needs.changes.outputs.algorithmic == 'true' }}
    runs-on: ubuntu-latest
    container:
      image: joennlae/halutmatmul-conda-gpu:latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v2
    - name: Check types with pyright 
      run: |
        source /venv/bin/activate
        pyright