name: PyTest
# https://autobencoder.com/2020-08-24-conda-actions/
on: [push]

jobs:
  changes:
    uses: ./.github/workflows/filter.yaml
  test_python:
    needs: changes
    if: ${{ needs.changes.outputs.algorithmic == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        split: [1, 2, 3, 4, 5]
    runs-on: ubuntu-latest
    container:
      image: joennlae/halutmatmul-conda-gpu:latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v2
    - name: Download Test data
      run: |
        apt-get -y update
        apt-get -y install curl
        cd maddness && bash ./download_assets.sh && cd ..
    - name: Test with pytest
      run: |
        source /venv/bin/activate
        pip install pytest-split
        df -h
        du -a / | sort -n -r | head -n 10
        pytest -srPA -k "not gpu" --splits 5 --group ${{ matrix.split }}
